# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master  # Only build for changes in master branch (and pull requests)

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g yarn
    yarn
  displayName: 'Install dependencies'

- script: |
    yarn test
  displayName: 'Run tests'

- script: |
    yarn build
  displayName: 'Build package'

- script: |
    rm -rf node_modules/
  displayName: 'Delete node_modules'

- task: PublishBuildArtifacts@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    pathtoPublish: '$(Build.SourcesDirectory)'
    artifactName: 'drop' 
    publishLocation: 'Container'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/junit.xml'
    testRunTitle: 'Publish test results for Jest'
